version: '3'

volumes:
 mongodb_data:

networks:
  default:
    ipam:
      config:
        - subnet: 172.30.1.0/24
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      default:
        ipv4_address: 172.30.1.12

  webui:
    image: open5gs_base:ub
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://172.30.1.12/open5gs
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000/tcp"
    expose:
      - "3000/tcp" 
    volumes:
        - "./config/webui:/etc/open5gs"
        - "./log:/var/log/open5gs"
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_webui.sh"
    networks:
      default:
        ipv4_address: 172.30.1.11

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=mongodb
    container_name: "dbprovisioner"
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      default:
        ipv4_address: 172.30.1.10

  nrf:
    image: open5gs_base:ub
    container_name: nrf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_nrf.sh"
    volumes:
      - ./config/nrf:/etc/open5gs
      - ./log:/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: 172.30.1.17

  ausf:
    image: open5gs_base:ub
    depends_on:
      - nrf
    container_name: ausf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_ausfm.sh"
    volumes:
      - ./config/ausf:/etc/open5gs
      - ./log:/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: 172.30.1.19
  
  udm:
    image: open5gs_base:ub
    depends_on:
      - nrf
    container_name: udm
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_udm.sh"
    volumes:
      - ./config/udm:/etc/open5gs
      - ./log:/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: 172.30.1.20

  udr:
    image: open5gs_base:ub
    depends_on:
      - nrf
      - mongodb
    container_name: udr
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_udr.sh"
    volumes:
      - ./config/udr:/etc/open5gs
      - ./log:/var/log/open5gs
    expose:
      - "7777/tcp"
    networks:
      default:
        ipv4_address: 172.30.1.14

  pcf:
    image: open5gs_base:ub
    depends_on:
      - nrf
      - mongodb
    container_name: pcf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pcf.sh"      
    expose:
      - "7777/tcp"
    volumes:
      - ./config/pcf:/etc/open5gs
      - ./log:/var/log/open5gs
    networks:
      default:
        ipv4_address: 172.30.1.15

  nssf:
    image: open5gs_base:ub
    depends_on:
      - nrf
      - mongodb
    container_name: nssf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_nssf.sh"      
    expose:
      - "7777/tcp"
    volumes:
      - ./config/nssf:/etc/open5gs
      - ./log:/var/log/open5gs
    networks:
      default:
        ipv4_address: 172.30.1.16

  hss:
    image: open5gs_base:ub
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_hss.sh"
    volumes:
      - "./config/hss:/etc/open5gs"
      - "./config/freeDiameter:/etc/freeDiameter"
      - "./log:/var/log/open5gs"
    networks:
      default:
        ipv4_address: 172.30.1.4

  mme:
    image: open5gs_base:ub
    depends_on:
      - hss
      - sgwc
      - sgwu
      - smf
      - upf
    container_name: mme
    hostname: mme
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_mme.sh"
    volumes:
      - "./config/mme:/etc/open5gs"
      - "./config/freeDiameter:/etc/freeDiameter"
      - "./log:/var/log/open5gs"
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "36412/sctp"
      - "2123/udp"
    networks:
      default:
        ipv4_address: 172.30.1.5
     
  sgwc:
    image: open5gs_base:ub
    depends_on:
      - upf   
    container_name: sgwc
    hostname: sgwc
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_sgwc.sh"
    volumes:
      - "./config/sgwc:/etc/open5gs"
      - "./config/freeDiameter:/etc/freeDiameter"
      - "./log:/var/log/open5gs"
    expose:
      - "2123/udp"
      - "8805/udp"
    networks:
      default:
        ipv4_address: 172.30.1.6

  sgwu:
    image: open5gs_base:ub
    depends_on:
      - upf   
    container_name: sgwu
    hostname: sgwu
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_sgwu.sh"
    volumes:
      - "./config/sgwu:/etc/open5gs"
      - "./config/freeDiameter:/etc/freeDiameter"
      - "./log:/var/log/open5gs"
    expose:
      - "8805/udp"
      - "2152/udp"
    networks:
      default:
        ipv4_address: 172.30.1.7

  smf:
    image: open5gs_base:ub
    depends_on:
      - nrf
    container_name: smf
    hostname: smf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_smf.sh"
    volumes:
      - "./config/smf:/etc/open5gs"
      - "./config/freeDiameter:/etc/freeDiameter"
      - "./log:/var/log/open5gs"
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
    networks:
      default:
        ipv4_address: 172.30.1.18

  upf:
    image: open5gs_base:ub
    container_name: upf
    hostname: upf
    privileged: true
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_upf.sh"
    volumes:
      - "./config/upf:/etc/open5gs"
      - "./log:/var/log/open5gs"

    cap_add:
      -  NET_ADMIN
    devices:
      - "/dev/net/tun"
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      default:
        ipv4_address: 172.30.1.8

  pcrf:
    image: open5gs_base:ub
    depends_on:
      - mongodb
    container_name: pcrf
    hostname: pcrf
    entrypoint:
      - "/bin/sh"
      - "/etc/open5gs/run_pcrf.sh"
    volumes:
      - "./config/pcrf:/etc/open5gs"
      - "./config/freeDiameter:/etc/freeDiameter"
      - "./log:/var/log/open5gs"
    networks:
       default:
         ipv4_address: 172.30.1.9
