logger:
    file: /var/log/open5gs/nssf.log

parameter:

nssf:
    sbi:
      - addr: 172.30.1.16
        port: 7777
    nsi:
      - addr: 172.30.1.17
        port: 7777
        s_nssai:
          sst: 1
nrf:
    sbi:
      - addr:
          - 172.30.1.17
        port: 7777
