apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf
  labels:
    app.kubernetes.io/part-of: open5gs
data:
  ausf.yaml: |
    logger:
    file: /var/log/open5gs/ausf.log

    parameter:

    ausf:
        sbi:
          - dev: eth0
            port: 7777

    nrf:
        sbi:
          - name: nrf
            port: 7777
