apiVersion: v1
data:
  sgwc.yaml: "logger:\n    file: /var/log/open5gs/sgwc.log\n    trace:\n        app:
    1\n        gtpv2: 1\n        gtp: 1\n\nparameter:\n    no_ipv6: true\n\nsgwc:\n
    \   gtpc:\n      - addr: 0.0.0.0\n    pfcp:\n      - addr: 0.0.0.0\n      \nsgwu:\n
    \   pfcp:\n      - addr: sgwu\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-05T15:34:27Z"
  labels:
    app.kubernetes.io/part-of: open5gs
    name: sgwc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:sgwc.yaml: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-05T15:34:27Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/part-of: {}
          f:name: {}
    manager: kubectl-label
    operation: Update
    time: "2021-07-05T15:34:58Z"
  name: sgwc
  namespace: default
  resourceVersion: "762619"
  uid: ee3e3c0a-500f-4f4d-a76c-6732f27287e5
