apiVersion: v1
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/ugf.log
        trace:
            app: 1
            diameter: 1
            gtpv2: 1
            gtp: 1

    parameter:
        no_ipv6: true

    upf:
        pfcp:
          - addr: 0.0.0.0
        gtpu:
          - addr: 0.0.0.0
        subnet:
          - addr: 45.45.0.1/16
            dev: ogstun
            dnn: internet
kind: ConfigMap
metadata:
  creationTimestamp: "2021-07-05T15:17:19Z"
  labels:
    app.kubernetes.io/part-of: open5gs
    name: upf
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:upf.yaml: {}
    manager: kubectl-create
    operation: Update
    time: "2021-07-05T15:17:19Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/part-of: {}
          f:name: {}
    manager: kubectl-label
    operation: Update
    time: "2021-07-05T15:17:59Z"
  name: upf
  namespace: default
  resourceVersion: "758484"
  uid: a9b7318b-9eb7-462d-80fb-7192c18cf396
