logger:
    file: /var/log/open5gs/mme.log
    level: trace

parameter:
    no_ipv6: true

mme:
    freeDiameter: /etc/freeDiameter/mme.conf
    s1ap:
      addr: 172.30.1.5
    gtpc:
      addr: 172.30.1.5
    gummei: 
      plmn_id:
        mcc: 001
        mnc: 01
      mme_gid: 2
      mme_code: 1
    tai:
      plmn_id:
        mcc: 001
        mnc: 01
      tac: 12345
    security:
        integrity_order : [ EIA1, EIA2, EIA0 ]
        ciphering_order : [ EEA0, EEA1, EEA2 ]
    network_name:
        full: Open5GS
    mme_name: open5GS-mme0

sgwc:
    gtpc:
      addr: 172.30.1.6

smf:
    gtpc:
      addr: 172.30.1.8
