apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /cfg
    server: kind-control-plane.local
    readOnly: false
