apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /log
    server: kind-control-plane.local
    readOnly: false
